============================= test session starts ==============================
platform linux -- Python 3.8.5, pytest-6.2.2, py-1.10.0, pluggy-0.13.1 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/gredfix/proizvod
plugins: Faker-6.6.0, cov-2.12.0
collecting ... collected 9 items

test_proizvod.py::test_validation[other_user_logs-0-2-30-ValueError] PASSED [ 11%]
test_proizvod.py::test_validation[other_user_logs-4--1-30-TypeError] PASSED [ 22%]
test_proizvod.py::test_validation[some_directory-4-2-30-FileNotFoundError] PASSED [ 33%]
test_proizvod.py::test_validation[other_user_logs-4-2.2-30-TypeError] PASSED [ 44%]
test_proizvod.py::test_default_work PASSED                               [ 55%]
test_proizvod.py::test_empty_file PASSED                                 [ 66%]
test_proizvod.py::test_bad_file[userIP.csv-ValueError] PASSED            [ 77%]
test_proizvod.py::test_bad_file[userDATE.csv-ValueError] PASSED          [ 88%]
test_proizvod.py::test_bad_file[userSITE.csv-IndexError] PASSED          [100%]

============================== 9 passed in 0.35s ===============================
